# Guttenbergovitz theme for Helix
# A warm, vintage-inspired theme matching jazz aesthetics

"ui.background" = { bg = "bg0" }
"ui.text" = "fg0"
"ui.virtual.whitespace" = { fg = "bg4" }
"ui.selection" = { bg = "bg3" }
"ui.cursor" = { fg = "fg0", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "fg0", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "yellow", modifiers = ["underlined"] }
"ui.linenr" = "bg4"
"ui.linenr.selected" = "fg0"
"ui.statusline" = { fg = "fg0", bg = "bg1" }
"ui.statusline.inactive" = { fg = "fg4", bg = "bg1" }
"ui.popup" = { bg = "bg1" }
"ui.window" = { bg = "bg1" }
"ui.help" = { bg = "bg1", fg = "fg0" }
"ui.menu" = { bg = "bg1", fg = "fg0" }
"ui.menu.selected" = { bg = "bg3", fg = "fg0" }
"ui.virtual.ruler" = { bg = "bg2" }

# Syntax highlighting
"comment" = { fg = "gray", modifiers = ["italic"] }
"constant" = "yellow"
"constant.numeric" = "yellow"
"constant.character.escape" = "orange"
"string" = "green"
"string.regexp" = "blue"
"string.special" = "blue"
"keyword" = "red"
"operator" = "red"
"function" = "orange"
"function.builtin" = "orange"
"function.method" = "orange"
"variable" = "fg0"
"variable.builtin" = "red"
"variable.parameter" = "fg0"
"variable.other.member" = "fg0"
"type" = "yellow"
"type.builtin" = "yellow"
"constructor" = "yellow"
"special" = "orange"
"label" = "red"

# Markup
"markup.heading" = "orange"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "green", modifiers = ["underlined"] }
"markup.link.text" = "blue"
"markup.raw" = "red"

# Diagnostics
"diagnostic" = { modifiers = ["underlined"] }
"diagnostic.error" = "red"
"diagnostic.warning" = "yellow"
"diagnostic.info" = "blue"
"diagnostic.hint" = "green"

[palette]
bg0 = "#232326"
bg1 = "#1d1d20"
bg2 = "#2a2a2d"
bg3 = "#3a3a3d"
bg4 = "#7c7c7c"

fg0 = "#d4be98"
fg4 = "#7c7c7c"

gray = "#7c7c7c"
red = "#a96b69"
green = "#89a87d"
yellow = "#d6b986"
blue = "#d79969"
orange = "#d79969"
magenta = "#a96b69"
cyan = "#89a87d" 